databases.resort_marketing_insights.datasources.jdbc.customvdpcachedatasource.DATABASEURI=jdbc\:derby\://devdenodo-9.iqzsystems.io\:1527/cache
databases.resort_marketing_insights.datasources.jdbc.customvdpcachedatasource.USERNAME=vdpcache
databases.resort_marketing_insights.datasources.jdbc.customvdpcachedatasource.USERPASSWORD=9X8WVFZldhQsDLRl7NmMy9Gd51YKX5SXctesdLUgkarytF2SkI6Wh5xRmGapgbHrO0okjfYxw9iHLoJjku+H0PUDH5L9fN1utr1Ueqw822nVoqHTNjKf2XLM3sUl6zkGup2rTxrsYZDxhdIk+HQNIQ\=\=
databases.resort_marketing_insights.datasources.jdbc.customvdpcachedatasource.USERPASSWORD.ENCRYPTED=ENCRYPTED
